version: "3.2"

# OpenVPN container automated test compose file.

services:
  rootca:
    image: lochnerr/openvpn:latest
    command: /usr/local/bin/openvpn-test-sshd
    restart: "no"
    hostname: rootca.example.com
    networks:
      - openvpn

  ca:
    image: lochnerr/openvpn:latest
    command: /usr/local/bin/openvpn-test-sshd
    restart: "no"
    hostname: ca.example.com
    networks:
      - openvpn

  vpn1:
    image: lochnerr/openvpn:latest
    privileged: true
    command: /usr/local/bin/openvpn-test-server ec  7111 10.77.123.0 3
    restart: "no"
    hostname: vpn1.example.com
    volumes:
      - test:/etc/shared
    networks:
      - openvpn

  vpn2:
    image: lochnerr/openvpn:latest
    privileged: true
    command: /usr/local/bin/openvpn-test-server rsa 7112 10.77.123.0 5
    restart: "no"
    hostname: vpn2.example.com
    volumes:
      - test:/etc/shared
    networks:
      - openvpn

  client1:
    image: lochnerr/openvpn:latest
    privileged: true
    command: /usr/local/bin/openvpn-test-client ec  7111 vpn1.example.com client1 active   10
    restart: "no"
    hostname: client1.example.com
    volumes:
      - test:/etc/shared
    networks:
      - openvpn

  client2:
    image: lochnerr/openvpn:latest
    privileged: true
    command: /usr/local/bin/openvpn-test-client ec  7111 vpn1.example.com client2 revoked  15
    restart: "no"
    hostname: client2.example.com
    volumes:
      - test:/etc/shared
    networks:
      - openvpn

  client3:
    image: lochnerr/openvpn:latest
    privileged: true
    command: /usr/local/bin/openvpn-test-client rsa 7112 vpn2.example.com client3 active   20
    restart: "no"
    hostname: client3.example.com
    volumes:
      - test:/etc/shared
    networks:
      - openvpn

  client4:
    image: lochnerr/openvpn:latest
    privileged: true
    command: /usr/local/bin/openvpn-test-client rsa 7112 vpn2.example.com client4 revoked  25
    restart: "no"
    hostname: client4.example.com
    volumes:
      - test:/etc/shared
    networks:
      - openvpn

  sut:
    image: lochnerr/openvpn:latest
    privileged: true
    command: /usr/local/bin/openvpn-test sut
    restart: "no"
    hostname: sut.example.com
    volumes:
      - test:/etc/shared
    networks:
      - openvpn
    depends_on:
      - rootca
      - ca

volumes:
  test:

networks:
  openvpn:

