version: "3.2"

# OpenVPN container automated test compose file.

services:
  rootca:
    image: lochnerr/openvpn:latest
    privileged: true
    command: /usr/local/bin/openvpn-test-sshd
    restart: "no"
    hostname: rootca.example.com
    networks:
      - openvpn

  ca:
    image: lochnerr/openvpn:latest
    privileged: true
    command: /usr/local/bin/openvpn-test-sshd
    restart: "no"
    hostname: ca.example.com
    networks:
      - openvpn

  vpn:
    image: lochnerr/openvpn:latest
    privileged: true
    command: /usr/local/bin/openvpn-test server
    restart: "no"
    hostname: vpn.example.com
    volumes:
      - test:/etc/openvpn
    networks:
      - openvpn
    depends_on:
      - ca

  sut:
    image: lochnerr/openvpn:latest
    privileged: true
    command: /usr/local/bin/openvpn-test sut
    restart: "no"
    hostname: sut.example.com
    volumes:
      - test:/etc/openvpn
    networks:
      - openvpn
    depends_on:
      - ca
      - vpn

volumes:
  test:

networks:
  openvpn:

